name: AutoBerapi Daily DM

on:
  schedule:
    # Runs every day at 10 AM UTC (adjust timezone as needed)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  send-dm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run bot
        env:
          TIKTOK_USERNAME: ${{ secrets.TIKTOK_USERNAME }}
          TIKTOK_PASSWORD: ${{ secrets.TIKTOK_PASSWORD }}
          TARGET_USERNAME: ${{ secrets.TARGET_USERNAME }}
          DM_MESSAGE: ${{ secrets.DM_MESSAGE }}
          HEADLESS: 'true'
        run: node send-dm.js

      - name: Upload screenshot on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: error-screenshot
          path: error-screenshot.png
